name: CI CD PIPELINE
on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main 

jobs:
   Build_server:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2 


    - name: Verify PHP Syntax
      run: |
        for file in $(find . -name "*.php"); do
          php -l $file;
        done

    - name: Validate HTML
      run: |
        sudo apt-get install -y tidy
        for file in $(find . -name "*.html"); do
          tidy -e $file;
        done

    - name: Install Node.js and stylelint
      run: |
          sudo apt-get install -y nodejs npm
          npm install -g stylelint stylelint-config-standard
      
    - name: Validate CSS
      run: |
        for file in $(find . -name "*.css"); do
            stylelint $file;
          done
  
   Testing_server:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: swe40006
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, pdo_mysql, mysqli

    # Step 3: Validate composer.json and composer.lock
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    # Step 4: Cache Composer packages
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Step 5: Remove vendor directory (optional)
    - name: Remove vendor directory
      run: rm -rf vendor

    # Step 6: Install dependencies
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress -vvv

    # Step 7: Dump autoload
    - name: Dump autoload
      run: composer dump-autoload

    # Step 8: Check vendor directory
    - name: List vendor directory
      run: ls -la vendor/phpunit/phpunit/src/

    # Step 9: Run PHPUnit tests
    - name: Run PHPUnit tests
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: swe40006
        DB_USERNAME: root
        DB_PASSWORD: password
      run: |
        vendor/bin/phpunit --testdox --debug tests/ProcessTest.php
        vendor/bin/phpunit --testdox --debug tests/GetAnnouncementsTest.php
        vendor/bin/phpunit --testdox --debug tests/TeacherTest.php

   Porduction_server:
     runs-on: ubuntu-latest
     steps:
      - name: Do Nothing
        run: echo "This is were prodution goes."

      
    
