name: Validate Composer and Run PHPUnit Tests

on:
  push:
    branches:
      - main

jobs:
  phpunit_tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: swe40006
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, pdo_mysql, mysqli

    # Step 3: Validate composer.json and composer.lock
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    # Step 4: Cache Composer packages
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Step 5: Remove vendor directory (optional)
    - name: Remove vendor directory
      run: rm -rf vendor

    # Step 6: Install dependencies
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress -vvv

    # Step 7: Dump autoload
    - name: Dump autoload
      run: composer dump-autoload

    # Step 8: Check vendor directory
    - name: List vendor directory
      run: ls -la vendor/phpunit/phpunit/src/

    # Step 9: Run PHPUnit tests
    - name: Run PHPUnit tests
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: swe40006
        DB_USERNAME: root
        DB_PASSWORD: password
      run: |
        vendor/bin/phpunit --testdox --debug tests/ProcessTest.php
        vendor/bin/phpunit --testdox --debug tests/GetAnnouncementsTest.php
        vendor/bin/phpunit --testdox --debug tests/LogoutTest.php
        vendor/bin/phpunit --testdox --debug tests/TeacherTest.php
